# Generated by Django 2.2.6 on 2019-11-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='context',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
