# Generated by Django 2.2.6 on 2019-11-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191119_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='context',
            field=models.TextField(default='foo', max_length=1000),
        ),
    ]
