# Generated by Django 2.2.6 on 2019-11-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload1', models.FileField(upload_to='uploads/')),
                ('upload2', models.FileField(upload_to='uploads/')),
                ('upload3', models.FileField(upload_to='uploads/')),
                ('upload4', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
