# Generated by Django 2.2.6 on 2019-11-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromeachterm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formterm',
            name='upload4',
            field=models.IntegerField(),
        ),
    ]
